# Generated by Django 5.2.4 on 2025-12-09 09:21

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GISLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(db_index=True, default='General', max_length=100)),
                ('source_file', models.CharField(blank=True, help_text='Original source file path', max_length=500)),
                ('source_crs', models.CharField(default='EPSG:4283', help_text='Original coordinate reference system', max_length=50)),
                ('min_zoom', models.IntegerField(default=10)),
                ('max_zoom', models.IntegerField(default=22)),
                ('style_color', models.CharField(default='#3388ff', max_length=20)),
                ('style_weight', models.FloatField(default=1.0)),
                ('style_opacity', models.FloatField(default=0.7)),
                ('style_fill_opacity', models.FloatField(default=0.2)),
                ('is_active', models.BooleanField(default=True)),
                ('feature_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'GIS Layer',
                'verbose_name_plural': 'GIS Layers',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CadastralLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('lot_number', models.CharField(blank=True, max_length=20, null=True)),
                ('plan_number', models.CharField(blank=True, max_length=30, null=True)),
                ('plan_label', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('area_sqm', models.FloatField(blank=True, help_text='Area in square meters', null=True)),
                ('lga', models.CharField(blank=True, max_length=100, null=True, verbose_name='Local Government Area')),
                ('parish', models.CharField(blank=True, max_length=100, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cadastral Lot',
                'verbose_name_plural': 'Cadastral Lots',
                'indexes': [models.Index(fields=['lot_number', 'plan_number'], name='atlas_cadas_lot_num_cc39f4_idx'), models.Index(fields=['lga'], name='atlas_cadas_lga_54283d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Suburb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suburb_name', models.CharField(db_index=True, max_length=100)),
                ('postcode', models.CharField(blank=True, db_index=True, max_length=10, null=True)),
                ('lga', models.CharField(blank=True, max_length=100, null=True, verbose_name='Local Government Area')),
                ('state', models.CharField(default='NSW', max_length=10)),
                ('area_sqkm', models.FloatField(blank=True, help_text='Area in square kilometers', null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Suburb',
                'verbose_name_plural': 'Suburbs',
                'ordering': ['suburb_name'],
                'indexes': [models.Index(fields=['suburb_name', 'postcode'], name='atlas_subur_suburb__0849d2_idx')],
            },
        ),
        migrations.CreateModel(
            name='GenericFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='atlas.gislayer')),
            ],
            options={
                'verbose_name': 'Generic Feature',
                'verbose_name_plural': 'Generic Features',
                'indexes': [models.Index(fields=['layer', 'feature_id'], name='atlas_gener_layer_i_b3e34c_idx')],
            },
        ),
    ]
